export interface CountryColors {
  name: string;
  flag: string;
  colors: string[];
}

const COUNTRY_MAP: Record<string, CountryColors> = {
  israel:        { name: 'Israel',        flag: '🇮🇱', colors: ['#003DA5', '#ffffff', '#003DA5'] },
  usa:           { name: 'USA',           flag: '🇺🇸', colors: ['#B22234', '#ffffff', '#3C3B6E'] },
  'united states': { name: 'United States', flag: '🇺🇸', colors: ['#B22234', '#ffffff', '#3C3B6E'] },
  france:        { name: 'France',        flag: '🇫🇷', colors: ['#002395', '#ffffff', '#ED2939'] },
  japan:         { name: 'Japan',         flag: '🇯🇵', colors: ['#ffffff', '#BC002D', '#ffffff'] },
  italy:         { name: 'Italy',         flag: '🇮🇹', colors: ['#009246', '#ffffff', '#CE2B37'] },
  greece:        { name: 'Greece',        flag: '🇬🇷', colors: ['#0D5EAF', '#ffffff', '#0D5EAF'] },
  spain:         { name: 'Spain',         flag: '🇪🇸', colors: ['#AA151B', '#F1BF00', '#AA151B'] },
  germany:       { name: 'Germany',       flag: '🇩🇪', colors: ['#000000', '#DD0000', '#FFCE00'] },
  brazil:        { name: 'Brazil',        flag: '🇧🇷', colors: ['#009c3b', '#FFDF00', '#002776'] },
  india:         { name: 'India',         flag: '🇮🇳', colors: ['#FF9933', '#ffffff', '#138808'] },
  thailand:      { name: 'Thailand',      flag: '🇹🇭', colors: ['#A51931', '#ffffff', '#2D2A4A'] },
  portugal:      { name: 'Portugal',      flag: '🇵🇹', colors: ['#006600', '#FF0000', '#FFD700'] },
  mexico:        { name: 'Mexico',        flag: '🇲🇽', colors: ['#006847', '#ffffff', '#CE1126'] },
  netherlands:   { name: 'Netherlands',   flag: '🇳🇱', colors: ['#AE1C28', '#ffffff', '#21468B'] },
  turkey:        { name: 'Turkey',        flag: '🇹🇷', colors: ['#E30A17', '#ffffff', '#E30A17'] },
  egypt:         { name: 'Egypt',         flag: '🇪🇬', colors: ['#CE1126', '#ffffff', '#000000'] },
  jordan:        { name: 'Jordan',        flag: '🇯🇴', colors: ['#007A3D', '#ffffff', '#CE1126'] },
  uk:            { name: 'UK',            flag: '🇬🇧', colors: ['#012169', '#ffffff', '#C8102E'] },
  'united kingdom': { name: 'United Kingdom', flag: '🇬🇧', colors: ['#012169', '#ffffff', '#C8102E'] },
  england:       { name: 'England',       flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', colors: ['#ffffff', '#CF142B', '#ffffff'] },
  switzerland:   { name: 'Switzerland',   flag: '🇨🇭', colors: ['#FF0000', '#ffffff', '#FF0000'] },
  austria:       { name: 'Austria',       flag: '🇦🇹', colors: ['#ED2939', '#ffffff', '#ED2939'] },
  australia:     { name: 'Australia',     flag: '🇦🇺', colors: ['#00008B', '#ffffff', '#FF0000'] },
  canada:        { name: 'Canada',        flag: '🇨🇦', colors: ['#FF0000', '#ffffff', '#FF0000'] },
  china:         { name: 'China',         flag: '🇨🇳', colors: ['#DE2910', '#FFDE00', '#DE2910'] },
  southkorea:    { name: 'South Korea',   flag: '🇰🇷', colors: ['#ffffff', '#003478', '#CD2E3A'] },
  'south korea': { name: 'South Korea',   flag: '🇰🇷', colors: ['#ffffff', '#003478', '#CD2E3A'] },
  argentina:     { name: 'Argentina',     flag: '🇦🇷', colors: ['#74ACDF', '#ffffff', '#74ACDF'] },
  colombia:      { name: 'Colombia',      flag: '🇨🇴', colors: ['#FCD116', '#003087', '#CE1126'] },
  peru:          { name: 'Peru',          flag: '🇵🇪', colors: ['#D91023', '#ffffff', '#D91023'] },
  morocco:       { name: 'Morocco',       flag: '🇲🇦', colors: ['#C1272D', '#006233', '#C1272D'] },
  uae:           { name: 'UAE',           flag: '🇦🇪', colors: ['#00732F', '#ffffff', '#000000', '#FF0000'] },
  'united arab emirates': { name: 'UAE', flag: '🇦🇪', colors: ['#00732F', '#ffffff', '#000000', '#FF0000'] },
  czech:         { name: 'Czech Republic',flag: '🇨🇿', colors: ['#D7141A', '#ffffff', '#11457E'] },
  'czech republic': { name: 'Czech Republic', flag: '🇨🇿', colors: ['#D7141A', '#ffffff', '#11457E'] },
  hungary:       { name: 'Hungary',       flag: '🇭🇺', colors: ['#CE2939', '#ffffff', '#477050'] },
  poland:        { name: 'Poland',        flag: '🇵🇱', colors: ['#ffffff', '#DC143C', '#ffffff'] },
  sweden:        { name: 'Sweden',        flag: '🇸🇪', colors: ['#006AA7', '#FECC02', '#006AA7'] },
  norway:        { name: 'Norway',        flag: '🇳🇴', colors: ['#EF2B2D', '#ffffff', '#002868'] },
  denmark:       { name: 'Denmark',       flag: '🇩🇰', colors: ['#C60C30', '#ffffff', '#C60C30'] },
  finland:       { name: 'Finland',       flag: '🇫🇮', colors: ['#ffffff', '#003580', '#ffffff'] },
  iceland:       { name: 'Iceland',       flag: '🇮🇸', colors: ['#003897', '#ffffff', '#D72828'] },
  ireland:       { name: 'Ireland',       flag: '🇮🇪', colors: ['#169B62', '#ffffff', '#FF883E'] },
  belgium:       { name: 'Belgium',       flag: '🇧🇪', colors: ['#000000', '#FAE042', '#EF3340'] },
  singapore:     { name: 'Singapore',     flag: '🇸🇬', colors: ['#EF3340', '#ffffff', '#EF3340'] },
  vietnam:       { name: 'Vietnam',       flag: '🇻🇳', colors: ['#DA251D', '#FFCD00', '#DA251D'] },
  indonesia:     { name: 'Indonesia',     flag: '🇮🇩', colors: ['#CE1126', '#ffffff', '#CE1126'] },
  malaysia:      { name: 'Malaysia',      flag: '🇲🇾', colors: ['#CC0001', '#ffffff', '#006EB1'] },
  philippines:   { name: 'Philippines',   flag: '🇵🇭', colors: ['#0038A8', '#ffffff', '#CE1126'] },
  newzealand:    { name: 'New Zealand',   flag: '🇳🇿', colors: ['#00247D', '#ffffff', '#CC142B'] },
  'new zealand': { name: 'New Zealand',   flag: '🇳🇿', colors: ['#00247D', '#ffffff', '#CC142B'] },
  romania:       { name: 'Romania',       flag: '🇷🇴', colors: ['#002B7F', '#FCD116', '#CE1126'] },
  croatia:       { name: 'Croatia',       flag: '🇭🇷', colors: ['#FF0000', '#ffffff', '#171796'] },
  'south africa':{ name: 'South Africa',  flag: '🇿🇦', colors: ['#007A4D', '#000000', '#FFB612', '#DE3831', '#002395'] },
  kenya:         { name: 'Kenya',         flag: '🇰🇪', colors: ['#006600', '#CC0000', '#000000'] },
  tanzania:      { name: 'Tanzania',      flag: '🇹🇿', colors: ['#1EB53A', '#000000', '#FCD116', '#00A3DD'] },
  ethiopia:      { name: 'Ethiopia',      flag: '🇪🇹', colors: ['#078930', '#FCDD09', '#DA121A'] },
  russia:        { name: 'Russia',        flag: '🇷🇺', colors: ['#ffffff', '#0039A6', '#D52B1E'] },
  ukraine:       { name: 'Ukraine',       flag: '🇺🇦', colors: ['#005BBB', '#FFD500', '#005BBB'] },
  georgia:       { name: 'Georgia',       flag: '🇬🇪', colors: ['#ffffff', '#FF0000', '#ffffff'] },
  armenia:       { name: 'Armenia',       flag: '🇦🇲', colors: ['#D90012', '#0033A0', '#F2A800'] },
  azerbaijan:    { name: 'Azerbaijan',    flag: '🇦🇿', colors: ['#0092BC', '#E8000D', '#00AF66'] },
  cyprus:        { name: 'Cyprus',        flag: '🇨🇾', colors: ['#ffffff', '#d47600', '#ffffff'] },
  malta:         { name: 'Malta',         flag: '🇲🇹', colors: ['#ffffff', '#CF142B', '#ffffff'] },
  slovakia:      { name: 'Slovakia',      flag: '🇸🇰', colors: ['#ffffff', '#0B4EA2', '#EE1C25'] },
  slovenia:      { name: 'Slovenia',      flag: '🇸🇮', colors: ['#003DA5', '#ffffff', '#E30A17'] },
  serbia:        { name: 'Serbia',        flag: '🇷🇸', colors: ['#C6363C', '#0C4076', '#ffffff'] },
  bulgaria:      { name: 'Bulgaria',      flag: '🇧🇬', colors: ['#ffffff', '#00966E', '#D01E28'] },
  albania:       { name: 'Albania',       flag: '🇦🇱', colors: ['#E41E20', '#000000', '#E41E20'] },
  'north macedonia': { name: 'North Macedonia', flag: '🇲🇰', colors: ['#CF2027', '#F8E400', '#CF2027'] },
  bosnia:        { name: 'Bosnia',        flag: '🇧🇦', colors: ['#002395', '#FECC02', '#ffffff'] },
  montenegro:    { name: 'Montenegro',    flag: '🇲🇪', colors: ['#D4AF37', '#D4000A', '#234F9A'] },
  kosovo:        { name: 'Kosovo',        flag: '🇽🇰', colors: ['#244AA5', '#E4A400', '#244AA5'] },
  luxembourg:    { name: 'Luxembourg',    flag: '🇱🇺', colors: ['#EF3340', '#ffffff', '#00A1DE'] },
  estonia:       { name: 'Estonia',       flag: '🇪🇪', colors: ['#0072CE', '#000000', '#ffffff'] },
  latvia:        { name: 'Latvia',        flag: '🇱🇻', colors: ['#9E3039', '#ffffff', '#9E3039'] },
  lithuania:     { name: 'Lithuania',     flag: '🇱🇹', colors: ['#FDB913', '#006A44', '#C1272D'] },
  belarus:       { name: 'Belarus',       flag: '🇧🇾', colors: ['#CF101A', '#4AA657', '#ffffff'] },
  moldova:       { name: 'Moldova',       flag: '🇲🇩', colors: ['#003DA5', '#FFD200', '#CC0001'] },
  cambodia:      { name: 'Cambodia',      flag: '🇰🇭', colors: ['#032EA1', '#E00025', '#032EA1'] },
  myanmar:       { name: 'Myanmar',       flag: '🇲🇲', colors: ['#FECB00', '#34B233', '#EA2839'] },
  nepal:         { name: 'Nepal',         flag: '🇳🇵', colors: ['#003893', '#DC143C', '#003893'] },
  'sri lanka':   { name: 'Sri Lanka',     flag: '🇱🇰', colors: ['#8D153A', '#DF8E1D', '#006B3F'] },
  maldives:      { name: 'Maldives',      flag: '🇲🇻', colors: ['#D21034', '#007E3A', '#ffffff'] },
  pakistan:      { name: 'Pakistan',      flag: '🇵🇰', colors: ['#01411C', '#ffffff', '#01411C'] },
  iran:          { name: 'Iran',          flag: '🇮🇷', colors: ['#239F40', '#ffffff', '#DA0000'] },
  iraq:          { name: 'Iraq',          flag: '🇮🇶', colors: ['#CE1126', '#ffffff', '#000000'] },
  'saudi arabia':{ name: 'Saudi Arabia',  flag: '🇸🇦', colors: ['#006C35', '#ffffff', '#006C35'] },
  kuwait:        { name: 'Kuwait',        flag: '🇰🇼', colors: ['#007A3D', '#ffffff', '#CE1126', '#000000'] },
  qatar:         { name: 'Qatar',         flag: '🇶🇦', colors: ['#8D1B3D', '#ffffff', '#8D1B3D'] },
  bahrain:       { name: 'Bahrain',       flag: '🇧🇭', colors: ['#CE1126', '#ffffff', '#CE1126'] },
  oman:          { name: 'Oman',          flag: '🇴🇲', colors: ['#DB161B', '#ffffff', '#009A44'] },
  lebanon:       { name: 'Lebanon',       flag: '🇱🇧', colors: ['#FF0000', '#ffffff', '#00A550'] },
  tunisia:       { name: 'Tunisia',       flag: '🇹🇳', colors: ['#E70013', '#ffffff', '#E70013'] },
  algeria:       { name: 'Algeria',       flag: '🇩🇿', colors: ['#006233', '#ffffff', '#D21034'] },
  libya:         { name: 'Libya',         flag: '🇱🇾', colors: ['#000000', '#E70013', '#239E46'] },
  sudan:         { name: 'Sudan',         flag: '🇸🇩', colors: ['#D21034', '#ffffff', '#000000', '#007229'] },
  ghana:         { name: 'Ghana',         flag: '🇬🇭', colors: ['#006B3F', '#FCD116', '#EF3340'] },
  nigeria:       { name: 'Nigeria',       flag: '🇳🇬', colors: ['#008751', '#ffffff', '#008751'] },
  senegal:       { name: 'Senegal',       flag: '🇸🇳', colors: ['#00853F', '#FDEF42', '#E31B23'] },
  madagascar:    { name: 'Madagascar',    flag: '🇲🇬', colors: ['#FC3D32', '#007E3A', '#ffffff'] },
  mauritius:     { name: 'Mauritius',     flag: '🇲🇺', colors: ['#EA2839', '#1A206D', '#FFD500', '#00A551'] },
  seychelles:    { name: 'Seychelles',    flag: '🇸🇨', colors: ['#003F87', '#FCD856', '#D62828', '#ffffff', '#007A00'] },
  cuba:          { name: 'Cuba',          flag: '🇨🇺', colors: ['#002A8F', '#ffffff', '#CF142B'] },
  jamaica:       { name: 'Jamaica',       flag: '🇯🇲', colors: ['#000000', '#FED100', '#007A5E'] },
  'dominican rep.': { name: 'Dominican Rep.', flag: '🇩🇴', colors: ['#002D62', '#ffffff', '#CE1126'] },
  'dominican republic': { name: 'Dominican Rep.', flag: '🇩🇴', colors: ['#002D62', '#ffffff', '#CE1126'] },
  'costa rica':  { name: 'Costa Rica',    flag: '🇨🇷', colors: ['#002B7F', '#ffffff', '#CE1126'] },
  panama:        { name: 'Panama',        flag: '🇵🇦', colors: ['#DA121A', '#ffffff', '#003893'] },
  ecuador:       { name: 'Ecuador',       flag: '🇪🇨', colors: ['#FFD100', '#003893', '#C10101'] },
  bolivia:       { name: 'Bolivia',       flag: '🇧🇴', colors: ['#D52B1E', '#F4E400', '#007A3D'] },
  uruguay:       { name: 'Uruguay',       flag: '🇺🇾', colors: ['#ffffff', '#72B5F2', '#ffffff'] },
  paraguay:      { name: 'Paraguay',      flag: '🇵🇾', colors: ['#D52B1E', '#ffffff', '#0038A8'] },
  venezuela:     { name: 'Venezuela',     flag: '🇻🇪', colors: ['#CF142B', '#00247D', '#EF3340'] },
  chile:         { name: 'Chile',         flag: '🇨🇱', colors: ['#D52B1E', '#ffffff', '#003F87'] },
}

// Hebrew aliases → canonical English key in COUNTRY_MAP
const HE_ALIASES: Record<string, string> = {
  'ישראל': 'israel',
  'ארצות הברית': 'united states',
  'צרפת': 'france',
  'גרמניה': 'germany',
  'איטליה': 'italy',
  'ספרד': 'spain',
  'פורטוגל': 'portugal',
  'יוון': 'greece',
  'בריטניה': 'united kingdom',
  'הולנד': 'netherlands',
  'בלגיה': 'belgium',
  'שוויץ': 'switzerland',
  'אוסטריה': 'austria',
  'שוודיה': 'sweden',
  'נורווגיה': 'norway',
  'דנמרק': 'denmark',
  'פינלנד': 'finland',
  'אירלנד': 'ireland',
  'פולין': 'poland',
  'הונגריה': 'hungary',
  'טורקיה': 'turkey',
  'מצרים': 'egypt',
  'ירדן': 'jordan',
  'איחוד האמירויות': 'uae',
  'מרוקו': 'morocco',
  'יפן': 'japan',
  'סין': 'china',
  'הודו': 'india',
  'תאילנד': 'thailand',
  'וייטנאם': 'vietnam',
  'סינגפור': 'singapore',
  'דרום קוריאה': 'south korea',
  'אוסטרליה': 'australia',
  'ניו זילנד': 'new zealand',
  'קנדה': 'canada',
  'מקסיקו': 'mexico',
  'ברזיל': 'brazil',
  'ארגנטינה': 'argentina',
  'רומניה': 'romania',
  'קרואטיה': 'croatia',
  'דרום אפריקה': 'south africa',
  'קניה': 'kenya',
  'טנזניה': 'tanzania',
  'אתיופיה': 'ethiopia',
  'רוסיה': 'russia',
  'אוקראינה': 'ukraine',
  'גאורגיה': 'georgia',
  'ארמניה': 'armenia',
  "אזרבייג'אן": 'azerbaijan',
  'קפריסין': 'cyprus',
  'מלטה': 'malta',
  'סלובקיה': 'slovakia',
  'סלובניה': 'slovenia',
  'סרביה': 'serbia',
  'בולגריה': 'bulgaria',
  'אלבניה': 'albania',
  'מקדוניה': 'north macedonia',
  'בוסניה': 'bosnia',
  'מונטנגרו': 'montenegro',
  'קוסובו': 'kosovo',
  'לוקסמבורג': 'luxembourg',
  'אסטוניה': 'estonia',
  'לטביה': 'latvia',
  'ליטא': 'lithuania',
  'בלרוס': 'belarus',
  'מולדובה': 'moldova',
  'פיליפינים': 'philippines',
  'קמבודיה': 'cambodia',
  'מיאנמר': 'myanmar',
  'נפאל': 'nepal',
  'סרי לנקה': 'sri lanka',
  'מלדיביים': 'maldives',
  'פקיסטן': 'pakistan',
  'איראן': 'iran',
  'עיראק': 'iraq',
  'ערב הסעודית': 'saudi arabia',
  'כווית': 'kuwait',
  'קטאר': 'qatar',
  'בחריין': 'bahrain',
  'עומאן': 'oman',
  'לבנון': 'lebanon',
  'תוניסיה': 'tunisia',
  "אלג'יריה": 'algeria',
  'לוב': 'libya',
  'סודן': 'sudan',
  'גאנה': 'ghana',
  'ניגריה': 'nigeria',
  'סנגל': 'senegal',
  'מדגסקר': 'madagascar',
  'מאוריציוס': 'mauritius',
  'איי שייכל': 'seychelles',
  'קובה': 'cuba',
  "ג'מייקה": 'jamaica',
  'הרפובליקה הדומיניקנית': 'dominican republic',
  'קוסטה ריקה': 'costa rica',
  'פנמה': 'panama',
  'אקוודור': 'ecuador',
  'בוליביה': 'bolivia',
  'אורוגוואי': 'uruguay',
  'פרגוואי': 'paraguay',
  'ונצואלה': 'venezuela',
  "צ'ילה": 'chile',
  "צ'כיה": 'czech republic',
  'אינדונזיה': 'indonesia',
  'מלזיה': 'malaysia',
}

// Shorthand / code aliases
const SHORT_ALIASES: Record<string, string> = {
  'il': 'israel',
  'us': 'united states',
  'uk': 'united kingdom',
  'gb': 'united kingdom',
  'de': 'germany',
  'fr': 'france',
  'it': 'italy',
  'es': 'spain',
  'pt': 'portugal',
  'gr': 'greece',
  'jp': 'japan',
  'cn': 'china',
  'in': 'india',
  'th': 'thailand',
  'au': 'australia',
  'ca': 'canada',
  'br': 'brazil',
  'tr': 'turkey',
  'eg': 'egypt',
  'jo': 'jordan',
  'ae': 'uae',
  'ma': 'morocco',
}

const DEFAULT_COLORS = ['#3B6E52', '#5CB87A', '#3B6E52']

export function getCountryColors(countries: string[]): { colors: string[]; flags: string[]; names: string[] } {
  const allColors: string[] = []
  const flags: string[] = []
  const names: string[] = []

  for (const raw of countries) {
    const trimmed = raw.trim()
    const lower = trimmed.toLowerCase()
    const key = COUNTRY_MAP[lower] ? lower
      : HE_ALIASES[trimmed] ?? SHORT_ALIASES[lower] ?? lower
    const entry = COUNTRY_MAP[key]
    if (entry) {
      allColors.push(...entry.colors)
      flags.push(entry.flag)
      names.push(entry.name)
    }
  }

  if (allColors.length === 0) {
    return { colors: DEFAULT_COLORS, flags: ['🌍'], names: Array.isArray(countries) ? countries : [] }
  }

  // De-duplicate adjacent identical colors
  const deduped = allColors.filter((c, i) => i === 0 || c !== allColors[i - 1])
  return { colors: deduped, flags, names }
}
